name: Commit Verification

on:
  push:
  pull_request:
permissions:
  actions: write
  checks: write
  contents: write
  deployments: write
  id-token: write
  issues: write
  discussions: write
  packages: write
  pages: write
  pull-requests: write
  repository-projects: write
  security-events: write
  statuses: write

jobs:
  CodeVerifierAndIndenter:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          path: lilia

      - name: Setup Lua
        uses: leafo/gh-actions-lua@v8.0.0
        with:
          luaVersion: "5.2"

      - name: Setup LuaRocks
        uses: leafo/gh-actions-luarocks@v4.0.0

      - name: Pull gluacheck
        uses: actions/checkout@v2
        with:
          repository: impulsh/gluacheck
          path: luacheck

      - name: Build gluacheck
        working-directory: luacheck
        run: luarocks make

      - name: Lint with gluacheck
        working-directory: lilia
        run: >-
          luacheck . --no-redefined
          --no-global --no-self
          --no-max-line-length --no-max-code-line-length
          --no-max-string-line-length --no-max-comment-line-length
          --no-max-cyclomatic-complexity

      - name: Set up Bash
        run: |
          sudo apt update
          sudo apt install -y unzip

      - name: Download GLuaFixer
        run: |
          echo "Downloading GLuaFixer..."
          curl -L -o glualint.zip https://github.com/FPtje/GLuaFixer/releases/download/1.28.0/glualint-1.28.0-x86_64-linux.zip
          unzip glualint.zip -d glualint
          mv glualint/glualint glualint_executable

      - name: Set execution permissions
        run: |
          echo "Setting execution permissions for GLuaFixer..."
          sudo chmod +x glualint_executable
        working-directory: "${{ github.workspace }}"

      - name: Run GLuaFixer on Lilia - Part 1
        run: |
          echo "Step 7: Running GLuaFixer pretty-print on 'gamemode' in 'lilia'..."
          sudo ./glualint_executable pretty-print lilia/gamemode/*
        working-directory: ${{ github.workspace }}
        shell: bash

      - name: Run GLuaFixer on Lilia - Part 2
        run: |
          echo "Step 7: Running GLuaFixer pretty-print on 'libraries' in 'lilia'..."
          sudo ./glualint_executable pretty-print lilia/libraries/*
        working-directory: ${{ github.workspace }}
        shell: bash

      - name: Run GLuaFixer on Lilia - Part 3
        run: |
          echo "Step 7: Running GLuaFixer pretty-print on 'modules' in 'modules' of 'lilia'..."
          sudo ./glualint_executable pretty-print lilia/modules/*
        working-directory: ${{ github.workspace }}
        shell: bash
      - name: Remove the GLuaFixer folder
        run: |
          echo "Removing the GLuaFixer folder..."
          rm -r glualint
      - name: Delete the zip file
        run: |
          echo "Deleting GLuaFixer.zip..."
          rm glualint.zip

      - name: Remove the documentation folder
        run: |
          echo "Removing the documentation folder..."
          rm -r documentation

      - name: Clone Wiki
        run: |
          echo "Cloning Wiki..."
          git clone https://github.com/Lilia-Framework/Lilia.wiki.git documentation

      - name: Commit changes
        run: |
          echo "Committing changes..."
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          if [[ -n "$(git status --porcelain)" ]]; then
            git add -A
            git commit -m "Linted Code & Synced Documentation"
            git push
          else
            echo "No changes to commit."
          fi
        working-directory: "${{ github.workspace }}/lilia"
