name: Deploy GitHub Pages

on:
  push:
    jobs:
      - build:
jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/main' && github.repository == 'bleonheart/LiliaTest' && success()
    steps:
      - uses: actions/checkout@v2
        with:
          path: lilia

      - uses: leafo/gh-actions-lua@v8.0.0
        with:
          luaVersion: "5.2"

      - uses: leafo/gh-actions-luarocks@v4.0.0

      - name: Pull LDoc
        uses: actions/checkout@v2
        with:
          repository: impulsh/LDoc
          path: ldoc

      - name: Build LDoc
        working-directory: ldoc
        run: luarocks make

      - name: Build documentation
        working-directory: lilia
        run: ldoc . --fatalwarnings

      - name: Copy assets
        working-directory: lilia
        run: |
          cp -v documentation/css/* documentation/html
          cp -v documentation/js/* documentation/html

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: lilia/documentation/html
          cname: https://lilia-framework.github.io/documentation
          name: Upload gh-pages to Another Repo

  upload:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        
      - name: Set up Git
        uses: actions/setup-git@v2
        with:
          repository: Lilia-Framework/Lilia-Framework.github.io
          token: ${{ secrets.PAT_TOKEN }}

      - name: Pull gh-pages branch
        run: git pull origin gh-pages

      - name: Push changes to destination repo
        run: |
          git push origin gh-pages
