name: LUA Checker
on: [push, pull_request]

jobs:
  LuaChecker:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        path: lilia

    - name: Use Node.js 16.x
      uses: actions/setup-node@v2
      with:
        node-version: '16'

    - uses: leafo/gh-actions-lua@v8.0.0
      with:
        luaVersion: "5.2"

    - uses: leafo/gh-actions-luarocks@v4.0.0

    - name: Pull gluacheck
      uses: actions/checkout@v2
      with:
        repository: impulsh/gluacheck
        path: luacheck

    - name: Build gluacheck
      working-directory: luacheck
      run: luarocks make

    - name: Lint
      working-directory: lilia
      run: luacheck .
