name: Documentation Notifications
on:
  push:
    paths:
      - "documentation/**"
  repository_dispatch:
    types: [documentation]
  gollum:

permissions:
  actions: write
  checks: write
  contents: write
  deployments: write
  id-token: write
  issues: write
  discussions: write
  packages: write
  pages: write
  pull-requests: write
  repository-projects: write
  security-events: write
  statuses: write

jobs:
  WikiNotify:
    runs-on: ubuntu-latest

    steps:
      - name: Echo Build
        run: echo "Running Notifier"

      - name: Notify discord
        uses: th0th/notify-discord@v0.4.1
        if: ${{ always() }}
        env:
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
          GITHUB_ACTOR: ${{ github.actor }}
          GITHUB_JOB_NAME: "Just Updated The Wiki!"
          GITHUB_JOB_STATUS: ${{ job.status }}
