name: LuaRocks Workflow

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install Lua and LuaRocks
      run: |
        sudo apt-get update -y
        sudo apt-get install -y lua5.3 lua5.3-dev luarocks
      shell: bash

    - name: Install Lua modules
      run: |
        luarocks install --local --tree lua_modules luasocket
        luarocks install --local --tree lua_modules htmlparser
      shell: bash

    - name: Set LUA_PATH environment variable
      run: |
        export LUA_PATH="$GITHUB_WORKSPACE/lua_modules/share/lua/5.3/?.lua;;"
      shell: bash

    - name: Retrieve Lua script from GitHub
      run: |
        curl -o script.lua https://raw.githubusercontent.com/bleonheart/gmod-globals-scraper/master/scraper.lua
      shell: bash

    - name: Run Lua script and generate dump
      run: |
        lua script.lua
      shell: bash

    - name: Upload output text file to repo root
      run: |
        mv globals.txt $GITHUB_WORKSPACE/globals.txt
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add globals.txt
        git commit -m "Add globals.txt" || true
        git push
      shell: bash
