name: Wiki Sync

on:
  push:
  pull_request:
jobs:
  WikiSync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Pull Wiki
        run: |
          mkdir wiki
          git clone https://github.com/Lilia-Framework/Lilia.wiki.git wiki
      - name: Commit and Push Changes
        run: |
          echo "Committing changes..."
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          if [[ -n "$(git status --porcelain)" ]]; then
            git add -A
            git commit -m "Synced Wiki Settings"
            git push
          else
            echo "No changes to commit."
          fi
