name: Wiki Sync

on:
  push:
  pull_request:

permissions:
  actions: write
  checks: write
  contents: write
  deployments: write
  id-token: write
  issues: write
  discussions: write
  packages: write
  pages: write
  pull-requests: write
  repository-projects: write
  security-events: write
  statuses: write

jobs:
  WikiSync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Clone or update Wiki
        run: |
          git clone https://github.com/Lilia-Framework/Lilia.wiki.git
          cd Lilia.wiki

      - name: Remove .git folder and Rename to "documentation"
        run: |
          mv Lilia.wiki documentation

      - name: Commit changes
        run: |
          echo "Committing changes..."
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"

          if [[ -n "$(git status --porcelain)" ]]; then
            git add -A
            git commit -m "Synced Documentation"

            curl -u ${{ secrets.GITHUB_TOKEN }} -X PATCH -H "Accept: application/vnd.github.v3+json" \
              --data '{"source": {"branch": "main"}, "name": "Home"}' \
              https://api.github.com/repos/Lilia-Framework/Lilia.wiki/pages/builds
          else
            echo "No changes to commit."
          fi
        working-directory: "${{ github.workspace }}"
