name: Wiki Sync

on:
  push:
  pull_request:

permissions:
  actions: write
  checks: write
  contents: write
  deployments: write
  id-token: write
  issues: write
  discussions: write
  packages: write
  pages: write
  pull-requests: write
  repository-projects: write
  security-events: write
  statuses: write

jobs:
  WikiSync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Clone or update Wiki
        run: |
          if [ -d "documentation" ]; then
            cd documentation
            git pull origin master
          else
            git clone https://github.com/Lilia-Framework/Lilia.wiki.git documentation
          fi

      - name: Commit and Push Changes
        run: |
          echo "Committing changes..."
          cd documentation
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          if [[ -n "$(git status --porcelain)" ]]; then
            git add -A
            git commit -m "Synced Documentation Files"
            git push origin master
          else
            echo "No changes to commit."
          fi
