name: Wiki Update

on:
  push:
    paths:
      - "development/documentation/**"
  pull_request:
    paths:
      - "development/documentation/**"

permissions:
  actions: write
  checks: write
  contents: write
  deployments: write
  id-token: write
  issues: write
  discussions: write
  packages: write
  pages: write
  pull-requests: write
  repository-projects: write
  security-events: write
  statuses: write

jobs:
  Wiki_Update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Check for Wiki Changes
        id: wiki-check
        run: |
          if git diff --quiet ${{ github.sha }} HEAD -- 'development/documentation/**'; then
            echo "No changes in the wiki."
            echo "has_changes=false" >> $GITHUB_ENV
          else
            echo "Changes detected in the wiki."
            echo "has_changes=true" >> $GITHUB_ENV
          fi

      - name: Publish Wiki
        if: env.has_changes == 'true'
        uses: spenserblack/actions-wiki@v0.3.0
        with:
          path: development/documentation
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Push Changes to Wiki Repository
        if: env.has_changes == 'true'
        run: |
          cd development/documentation
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor }}@users.noreply.github.com"
          git add .
          git commit -m "Auto-commit changes to the wiki."
          git push origin HEAD:${{ github.event_name }}
