name: Wiki Update

on:
  push:
    paths:
      - "development/documentation/**"
      - ".github/workflows/**"
  pull_request:
    paths:
      - "development/documentation/**"
      - ".github/workflows/**"

jobs:
  wiki_update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Clone Wiki
        run: git clone https://github.com/Lilia-Framework/Lilia.wiki.git temp_dev

      - name: Check for Wiki Changes
        id: wiki-check
        run: |
          if git diff --quiet development/documentation temp_dev; then
            echo "No changes in the wiki."
            echo "has_changes=false" >> $GITHUB_ENV
          else
            echo "Changes detected in the wiki."
            echo "has_changes=true" >> $GITHUB_ENV
          fi

      - name: Push Changes if Needed
        if: env.has_changes == 'true'
        run: |
          cd development/documentation
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor }}@users.noreply.github.com"
          git add .
          git commit -m "Auto-commit changes to the wiki."
          git push origin HEAD:${{ github.event_name }}
